### ISSUE TITLE
SegFault on loading an environment

### ISSUE THREAD

**Issue by HenryZhou7** [deepmind/dm_control#16] opened 2018-01-12 16:27 UTC
'''
>>> from dm_control import suite
>>> env = suite.load(domain_name='cartpole', task_name='swingup')
Segmentation fault (core dumped)
'''

I can import a suite but cannot load a testing environment.

**Comment by wookayin** [comment] 2018-01-13 15:29
#2

**Comment by saran-t** [comment] 2018-03-19 15:53
Since you didn't provide your system spec here, I am going to assume that this is a duplicate of #2. Please try the workaround suggested there, and provide us with further comments if it doesn't work.

**Closed by saran-t** 2018-03-19 15:53 UTC
