### ISSUE TITLE
new domain with STL mesh

### ISSUE THREAD

**Issue by foolyc** [deepmind/dm_control#11] opened 2018-01-08 10:22 UTC
how to create a new domain with STL mesh file?
when i tried to add mesh file to the domain xml file, Segmentation fault (core dumped) will come out.
while removing the asset it is normal.

**Comment by isacarnekvist** [comment] 2018-01-09 08:58
+1

**Comment by yotam** [comment] 2018-01-09 10:10
Assuming you have a mesh imported in the MJCF file as

    <asset>
      <mesh name="meshname"   file="filename.stl"/>
    </asset>

where the `.stl` filename is specified relative to the MJCF/XML file. For a quick check, try to load the MJCF file in the `simulate` example provided with MuJoCo Pro.

Once that all works, you can use the named constructor [`mujoco.Physics.from_xml_path`](https://github.com/deepmind/dm_control/blob/3b9bf0aa6c910c668e5bb0dc2414f00738d90bb1/dm_control/mujoco/engine.py#L353), passing the path to the MJCF file.

Alternatively, you can pass the MJCF file contents to [`mujoco.Physics.from_xml_string`](https://github.com/deepmind/dm_control/blob/3b9bf0aa6c910c668e5bb0dc2414f00738d90bb1/dm_control/mujoco/engine.py#L330) and use the `assets` argument to supply the `.stl` data.

**Comment by foolyc** [comment] 2018-01-10 07:13
yes, i tried my xml in simulate provided with MuJoCo Pro, it works well.

**Comment by foolyc** [comment] 2018-01-11 03:27
yes, i tried my xml(both with STL or with out STL) in simulate provided with MuJoCo Pro, it works well.
But the  `mujoco.Physics.from_xml_path` and  `mujoco.Physics.from_xml_string` fail.

**Comment by alimuldal** [comment] 2018-01-22 23:22
Sorry, didn't mean to close this. Could you share the problem STL mesh as well as the XML file?

**Comment by alimuldal** [comment] 2018-03-23 19:17
Closing this for now since we haven't heard back from the OP and we lack the XML and STL file needed to reproduce the segfault. Please reopen and provide the missing info if this is still an issue.

**Closed by alimuldal** 2018-03-23 19:17 UTC
