### ISSUE TITLE
missed files

### ISSUE THREAD

**Issue by yueyue-yue** [deepmind/dm_control#166] opened 2021-01-26 16:19 UTC
from dm_control.mujoco.wrapper.mjbindings import constants
from dm_control.mujoco.wrapper.mjbindings import enums
from dm_control.mujoco.wrapper.mjbindings import sizes
from dm_control.mujoco.wrapper.mjbindings import types
from dm_control.mujoco.wrapper.mjbindings import wrappers

missed files 'constants', 'enums', 'sizes', 'types', 'wrappers'

**Comment by yueyue-yue** [comment] 2021-01-26 16:20
location: dm_control/mujoco/wrapper/mjbindings/__init__.py

**Comment by yueyue-yue** [comment] 2021-01-26 17:02
ImportError: 
cannot import name 'constants' from partially initialized module 'dm_control.mujoco.wrapper.mjbindings' (most likely due to a circular import) 
(/home/xxx/dm_control/mujoco/wrapper/mjbindings/__init__.py)

**Comment by yueyue-yue** [comment] 2021-01-26 17:03
When running files in deep mind research/catch-carry, this mistake always occur.

**Comment by alimuldal** [comment] 2021-01-26 19:32
Possible duplicate of  #6. Those source files are normally generated automatically when you `pip install <path to dm_control>`.

**Comment by yueyue-yue** [comment] 2021-01-27 11:47
Thank you and I have fixed this successfully. But sorry to brother again, a new problem emerged:
'''
WARNING:absl:mjbindings failed to import mjlib and other functions. libmujoco.so may not be accessible.
...
...
OSError: /home/user/.mujoco/mujoco200_linux/bin/libmujoco200.so: undefined symbol: __glewBindBuffer
'''
My mujoco engine can work well seperately and the location of the mujoco files are located at default paths.

**Comment by alimuldal** [comment] 2021-01-27 11:53
That error means that libglew is not being found - perhaps you need to install it? See the instructions here: https://github.com/deepmind/dm_control#rendering

**Closed by alimuldal** 2021-01-27 11:53 UTC

**Comment by mingyucai** [comment] 2021-05-06 05:23
when I do "from dm_control import suite" I got the error: 
'''
cannot import name 'constants' from partially initialized module 'dm_control.mujoco.wrapper.mjbindings' (most likely due to a circular import) (/home/mingyu/dm_control/dm_control/mujoco/wrapper/mjbindings/__init__.py)
'''
My system is Ubuntu 20 and I have installed libglew2.1, which is not libglew2.0. I don't know the issues.

**Comment by mingyucai** [comment] 2021-05-06 05:26
I also strictly follow the instruction 'pip3 install . --user'. But still can got the error
'''
ImportError:
cannot import name 'constants' from partially initialized module 'dm_control.mujoco.wrapper.mjbindings' (most likely due to a circular import)
(/home/xxx/dm_control/mujoco/wrapper/mjbindings/init.py)
""

**Comment by mingyucai** [comment] 2021-05-06 05:47
I solved the issue. I found after pip install, the python locate the dm_control module in the download folder, not the python package folder.

**Comment by mingyucai** [comment] 2021-05-06 05:48
Thanks for the great source.

**Comment by yueyue-yue** [comment] 2021-05-06 07:32
Thanks a lot!!!
Best Wishes!!
________________________________
发件人: mingyucai ***@***.***>
发送时间: 2021年5月6日 13:48
收件人: deepmind/dm_control ***@***.***>
抄送: Yue Zenglin ***@***.***>; Author ***@***.***>
主题: Re: [deepmind/dm_control] missed files (#166)

        - External Email -



Thanks for the great source.

―
